localeChangers:
  localeEmulator:
    enabled: false
    exec: 'D:\LocaleEmulator\LEProc.exe %GAME_PATH%'
    name: Locale Emulator
  noChanger:
    enabled: true
    exec: '%GAME_PATH%'
    name: 不转换
  ntleas:
    enabled: false
    exec: 'D:\ntleas046_x64\x86\ntleas.exe %GAME_PATH%'
    name: Ntleas
onlineApis:
  - enabled: false
    method: POST
    name: baidu
    needSession: false
    requestBodyFormat: 'X^{"query": %TEXT%, "from": "jp", "to": "zh"}'
    responseBodyPattern: 'O^%RESPONSE%.data[0].dst'
    url: 'http://fanyi.baidu.com/transapi'
  - enabled: false
    method: POST
    name: googleCN
    needSession: false
    requestBodyFormat: 'X^{"q": %TEXT%, "sl": "ja", "hl": "zh-CN"}'
    responseBodyPattern: R^/class="t0">(.*)</
    url: 'https://translate.google.cn/m'
  - enabled: false
    external: true
    jsFile: config\youdaoApi.js
    name: youdao
translators:
  jBeijing:
    enabled: false
    path: 'D:\Visual Novel Reader V2\JBeijing7'
