pid: 12012

translators:
  jBeijing:
    enabled: false
    path: D:\Visual Novel Reader V2\JBeijing7

localeChanger:
  localeEmulator:
    enabled: true
    exec: D:\LocaleEmulator\LEProc.exe %GAME_EXEC%
  ntleas:
    enabled: false
    exec: D:\ntleas046_x64\x86\ntleas.exe %GAME_EXEC%

onlineApis:
  - name: baidu
    enabled: false
    url: http://fanyi.baidu.com/transapi
    needSession: false
    method: POST
    requestBodyFormat: 'X^{"query": %TEXT%, "from": "jp", "to": "zh"}'
    responseBodyPattern: 'O^%RESPONSE%.data[0].dst'

  - name: googleCN
    enabled: false
    url: https://translate.google.cn/m
    needSession: false
    method: POST
    requestBodyFormat: 'X^{"q": %TEXT%, "sl": "ja", "hl": "zh-CN"}'
    responseBodyPattern: 'R^/class="t0">(.*)</'

  - name: youdao
    enabled: false
    external: true
    jsFile: config\youdaoApi.js