localeChangers:
  alphaROMdiE:
    enable: true
    exec: 'D:\software\AlphaROMdiE.exe %GAME_PATH%'
    name: AlphaROMdiE
  localeEmulator:
    enable: false
    exec: 'D:\LocaleEmulator\LEProc.exe %GAME_PATH%'
    name: Locale Emulator
  noChanger:
    enable: false
    exec: "%GAME_PATH%"
    name: 不转换
  ntleas:
    enable: false
    exec: 'D:\ntleas046_x64\x86\ntleas.exe %GAME_PATH%'
    name: Ntleas
onlineApis:
  - enable: true
    method: POST
    name: baidu
    needSession: false
    requestBodyFormat: 'X{"query": %TEXT%, "from": "jp", "to": "zh"}'
    responseBodyPattern: "J%RESPONSE%.data[0].dst"
    url: "https://fanyi.baidu.com/transapi"
  - enable: true
    method: POST
    name: googleCN
    needSession: false
    requestBodyFormat: 'X{"q": %TEXT%, "sl": "ja", "hl": "zh-CN"}'
    responseBodyPattern: 'Rclass="t0">([^<]*)<'
    url: "https://translate.google.cn/m"
  - enable: false
    external: true
    jsFile: config\youdaoApi.js
    name: youdao
translators:
  jBeijing:
    enable: false
    path: 'D:\Visual Novel Reader V2\JBeijing7'
