games:
  - code: ''
    name: mahoXroba
    path: 'D:\Program Files\あかべぇそふとすりぃ\まほ×ろば -Witches spiritual home-\mahoXroba.exe'
  - code: ''
    name: 処女はお姉さまに恋してる３
    path: 'D:\Program Files\処女はお姉さまに恋してる３\処女はお姉さまに恋してる３.exe'
